config/routes.rb
Ishackproperties::Application.routes.draw do
  resources :avail_properties

  match 'sitemap.xml' => 'sitemaps#sitemap'

  resources :properties

  devise_for :users
  
  match '/about',to: 'properties#about'
  match '/contact',to: 'properties#contact'
  match '/availableproperties',to: 'properties#available'
  match '/home',to: 'properties#home'
  
  authenticated :user do
    root :to => 'properties#home'
  end

  root :to => 'properties#home'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :asset_content_type, :asset_file_name, :asset_file_size, :asset_updated_at, :property_id,:asset,
                  :caption
  
  belongs_to :property
  
  has_attached_file :asset, :styles => { :large => "640x480", :medium => "300x300>", :custom => "300x300>",
     :thumb => "100x100>" }
end

app/models/avail_property.rb
class AvailProperty < ActiveRecord::Base
  attr_accessible :available_units, :location, :name, :sold_out_units, :total_number_of_units, :unit_price
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :location, :name, :price, :status, :assets_attributes ,:asset,:quantity
  
  has_many :assets
  accepts_nested_attributes_for :assets, :allow_destroy => true   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/avail_properties_controller.rb
class AvailPropertiesController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:edit, :create, :update]
  # GET /avail_properties
  # GET /avail_properties.json
  def index
    @avail_properties = AvailProperty.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @avail_properties }
    end
  end

  # GET /avail_properties/1
  # GET /avail_properties/1.json
  def show
    @avail_property = AvailProperty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @avail_property }
    end
  end

  # GET /avail_properties/new
  # GET /avail_properties/new.json
  def new
    @avail_property = AvailProperty.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @avail_property }
    end
  end

  # GET /avail_properties/1/edit
  def edit
    @avail_property = AvailProperty.find(params[:id])
  end

  # POST /avail_properties
  # POST /avail_properties.json
  def create
    @avail_property = AvailProperty.new(params[:avail_property])

    respond_to do |format|
      if @avail_property.save
        format.html { redirect_to avail_properties_path }
        format.json { render json: @avail_property, status: :created, location: @avail_property }
      else
        format.html { render action: "new" }
        format.json { render json: @avail_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /avail_properties/1
  # PUT /avail_properties/1.json
  def update
    @avail_property = AvailProperty.find(params[:id])

    respond_to do |format|
      if @avail_property.update_attributes(params[:avail_property])
        format.html { redirect_to avail_properties_path }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @avail_property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avail_properties/1
  # DELETE /avail_properties/1.json
  def destroy
    @avail_property = AvailProperty.find(params[:id])
    @avail_property.destroy

    respond_to do |format|
      format.html { redirect_to avail_properties_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:edit, :create, :update]
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    @properties.each do |property|
      property.assets.build 
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])
    5.times { @property.assets.build }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new
    5.times { @property.assets.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
    5.times { @property.assets.build }
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])
    @property.user_id = current_user.id
    
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
  
  # Action for about us page.
  def about
    
  end
  
  # Action for Contact page.
  def conact
    
  end
  
  # Shows available properties
  def available
    @properties = Property.all
  end
  
  # Displays the websites home page.
  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
  case level
  when :notice then 'info'
  when :error then 'error'
  when :alert then 'warning'
  end
  end
end

app/helpers/avail_properties_helper.rb
module AvailPropertiesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/avail_properties/_form.html.erb
<%= form_for(@avail_property) do |f| %>
  <% if @avail_property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@avail_property.errors.count, "error") %> prohibited this avail_property from being saved:</h2>

      <ul>
      <% @avail_property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br />
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :total_number_of_units %><br />
    <%= f.text_field :total_number_of_units %>
  </div>
  <div class="field">
    <%= f.label :sold_out_units %><br />
    <%= f.text_field :sold_out_units %>
  </div>
  <div class="field">
    <%= f.label :available_units %><br />
    <%= f.text_field :available_units %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avail_properties/edit.html.erb
<div class="span8 center">
	<h2 class="page-header">Edit Available Property</h2>
	
	<%= render 'form' %>

	<%= link_to 'Back', avail_properties_path %>
</div>

app/views/avail_properties/index.html.erb
  <div class="span8 center">
  	<h2 class="page-header">Available Properties</h2>
  	<br />
  	<br />
	 <table class="table table-striped table-bordered">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Unit Price</th>
	      <th>Total Number of Units.</th>
	      <th>Sold out Units</th>
	      <th>Available</th>
	      <th>Location</th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
		
		<% @avail_properties.each do |avail_property| %>
		  <tr>
		    <td><%= avail_property.name %></td>
		    <td><%= avail_property.unit_price %></td>
		    <td><%= avail_property.total_number_of_units %></td>
		    <td><%= avail_property.sold_out_units %></td>
		    <td><%= avail_property.available_units %></td>
		    <td><%= avail_property.location %></td>
		    <% if user_signed_in? %>
		    	<td><%= link_to 'Edit', edit_avail_property_path(avail_property) %></td>
		    	<td><%= link_to 'Destroy', avail_property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		   <% end %>
		  </tr>
		<% end %>
	  </tbody>
	</table>
	
	<br />
	<% if user_signed_in? %>
		<%= link_to 'Add New Property', new_avail_property_path %>
	<% end %>
  </div>

app/views/avail_properties/new.html.erb
<div class="span8 center">
	<h2 class="page-header">Create New Available Property</h2>
	<%= render 'form' %>

	<%= link_to 'Back', avail_properties_path %>
</div>

app/views/avail_properties/show.html.erb
<div class="span8 center">
	<h2 class="page-header"><%= @avail_property.name %></h2>
	
	<p id="notice"><%= notice %></p>
	
	<p>
	  <b>Name:</b>
	  <%= @avail_property.name %>
	</p>
	
	<p>
	  <b>Unit price:</b>
	  <%= @avail_property.unit_price %>
	</p>
	
	<p>
	  <b>Total number of units:</b>
	  <%= @avail_property.total_number_of_units %>
	</p>
	
	<p>
	  <b>Sold out units:</b>
	  <%= @avail_property.sold_out_units %>
	</p>
	
	<p>
	  <b>Available units:</b>
	  <%= @avail_property.available_units %>
	</p>
	
	<p>
	  <b>Location:</b>
	  <%= @avail_property.location %>
	</p>
	
	<% if user_signed_in? %>
		<%= link_to 'Edit', edit_avail_property_path(@avail_property) %> <% end %>|
	<%= link_to 'Back', avail_properties_path %>
	
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
    	<p>&copy; IshackProperties 2013</p>
    	
	</small>
	<nav>
		<ul>
			<li>
				<p>
					Designed by
					<a href="https://www.facebook.com/gkitili">Gideon Kitili</a href="#"> And  <a> Eve Gitonga</a> 
				</p>
			</li>
			
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
 <div class="masthead">
    <%= link_to image_tag("_logo.jpg"), home_path %>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <ul class="nav">
            <li class="active">
            	<%= link_to "Home", home_path %>
            </li>
            
            <li>
            	<%= link_to "Properties", properties_path %>
            </li>
            <li>
            	<%= link_to "About Us", about_path %>
            </li>
            <li>
            	<%= link_to "Contact Us", contact_path %>
            </li>
            
            <li>
            	<%= link_to "Available Property", avail_properties_path %>
            </li>
            <li>
            	<% if user_signed_in? %>
            		<%= link_to "Logout", destroy_user_session_path, :method=>'delete' %>
            	<% else%>
            	    <%= link_to "Login", new_user_session_path %>
            	<% end %>
            </li>
            <li>
            	<% if user_signed_in? %>
        			<%= link_to "New Property", new_property_path %>
            	<% end %>
      	
            </li>
            <li>
            	<% if user_signed_in? %>
        			<%= link_to "Staff Mail", 'https://login.secureserver.net', :target => "_blank" %>
            	<% end %>
      	
            </li>
          </ul>
        </div>
      </div>
    </div><!-- /.navbar -->
  </div>

app/views/layouts/_marketing.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
    <h1>Welcome!</h1>
    <p class="lead">
    	Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
    </p>
    <a class="btn btn-large btn-success" href="#">Get started today</a>
</div>

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Sidebar</li>
      <li><p>Available Properties</p></li>
      <li><%= link_to "Login", new_user_session_path  %></li>
    </ul>
</div><!--/.well -->

app/views/layouts/_slideshow.html.erb
<div id="myCarousel" class="carousel slide">

    <div class="carousel-inner">
      <div class="item active">
        <%= image_tag("slide1.jpg") %>
        <div class="carousel-caption">
          <h4>First Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
      <div class="item">
        <%= image_tag("slide1.jpg") %>
        <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
      <div class="item">
        <%= image_tag("slide2.jpg") %>
        <div class="carousel-caption">
          <h4>Third Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>
</div>

app/views/layouts/_temp.html.erb
<div class="span4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
    <div class="span4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn" href="#">View details &raquo;</a></p>
   </div>
    <div class="span4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Ishackproperties</title>
    <%= csrf_meta_tags %>
    
    <% set_meta_tags :description => "Ishack properties is real eastate and property management company in Kenya. Find pieces of land and other properties for sale and to let here., Ishack properti, Kenya, Property for sale, Property to let, Nairobi Land" %>
    <% set_meta_tags :keywords => %w[ishack ishackproperties land kenya to let real eastate nairobi property properties Kenya Ishackproperties] %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
  	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	
     <div class="container">
		<%= render 'layouts/header' %>
		
      <!-- Example row of columns -->
      <div class="row" id="cont-back">
        <% [:notice, :error, :alert].each do |level| %>
            <% unless flash[level].blank? %>
              <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <%= content_tag :p, flash[level] %>
              </div>
            <% end %>
          <% end %>
          <%= yield %>
	  </div>
	  
      <%= render 'layouts/footer'%>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/properties/_form.html.erb
<div class="clearfix">
   <%= f.label :name, t("activerecord.attributes.property.name", :default => "Name") %>
  <div class="input">
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :description, t("activerecord.attributes.property.description", :default => "Description"), :class => :label %>
  <div class="input">
    <%= f.text_area :description, :class => 'text_area' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :location, t("activerecord.attributes.property.location", :default => "Location"), :class => :label %>
  <div class="input">
    <%= f.text_field :location, :class => 'text_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :status, t("activerecord.attributes.property.status", :default => "Status"), :class => :label %>
  <div class="input">
  	<%= f.select :status, [['Available','available'],['Sold','sold']], :class => 'text_field'%>
  </div>
</div>

<div class="clearfix">
   <%= f.label :price, t("activerecord.attributes.property.price", :default => "Price"), :class => :label %>
  <div class="input">
    <%= f.number_field :price, :class => 'number_field' %>
  </div>
</div>

<div class="clearfix">
   <%= f.label :quantity, t("activerecord.attributes.property.price", :default => "Available Quantity"), :class => :label %>
  <div class="input">
    <%= f.number_field :quantity, :class => 'number_field' %>
  </div>
</div>

<div class="clearfix">
    <h4>New Files</h4>
	
	<%= f.fields_for :assets do |asset_fields| %>
	
		<% if asset_fields.object.new_record? %>
		<p>
			<%= asset_fields.file_field :asset %>
			<%= asset_fields.text_field :caption, :class => 'text_area',:placeholder =>'Image caption' %>
		</p>
		<% end %>
	
	<% end %>
</div>

<div class="clearfix">
    <h4>Your Files</h4>	
	<ul class="thumbnails">
		<%= f.fields_for :assets do |asset_fields| %>
			<% unless asset_fields.object.new_record? %>
			  <li class="span4">
			    <div class="thumbnail">
			      <%= link_to image_tag(asset_fields.object.asset.url(:large)), '#' %>
				  <%= asset_fields.check_box :_destroy %>	
			      <h3>
			      	<%= @property.name %>
			      </h3>
			      <p>
			      	<%= truncate(strip_tags(asset_fields.object.caption),:length => 100) %>
			      </p>
			    </div>
			  </li>
			<% end %>
		<% end %>
	</ul>
</div>


<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", properties_path %>
</div>

app/views/properties/available.html.erb
  <div class="span8 center">
  	<h2 class="page-header">Available Property</h2>
  	<br />
  	<br />
	 <table class="table table-striped table-bordered">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Unit Price</th>
	      <th>Total Number of Units.</th>
	      <th>Sold out Units</th>
	      <th>Available</th>
	      <th>Location</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<tr>
	      <td>Ruiru 1/8</td>
	      <td>From KSH 1,500,000 per 1/8</td>
	      <td>10</td>
	      <td>-</td>
	      <td>10</td>
	      <td>Ruiru</td>
	    </tr>
	    <tr>
	      <td>Kipeto 1/8</td>
	      <td>From KSH 300,000 per 1/8</td>
	      <td>1</td>
	      <td>-</td>
	      <td>1</td>
	      <td>Kipeto</td>
	    </tr>
	    <tr>
	      <td>Juja athi 1/8</td>
	      <td>From KSH 270,000 per 1/8</td>
	      <td>24</td>
	      <td> - </td>
	      <td>24</td>
	      <td>Juja</td>
	    </tr>
	    <tr>
	      <td>Juja mung'etho 1/8</td>
	      <td>From KSH 270,000 per 1/8</td>
	      <td>24</td>
	      <td>8</td>
	      <td>16</td>
	      <td>Juja</td>
	    </tr>
	    <tr>
	      <td>Juja veritas</td>
	      <td>From KSH 500,000 per 1/8</td>
	      <td>24</td>
	      <td> - </td>
	      <td>24</td>
	      <td>Juja</td>
	    </tr>
	    <tr>
	      <td>Kisaju</td>
	      <td>From KSH 500,000 per 1/8</td>
	      <td>5</td>
	      <td> - </td>
	      <td>5</td>
	      <td>Kisaju</td>
	    </tr>
	    
	  </tbody>
	</table>
  </div>

app/views/properties/contact.html.erb
<div class="row">
  <div class="span2">
  	<p></p>
  </div>
  <div class="span8">
  	<h2 class="page-header">Contact Us</h2>
  	<h6>You may reach us on the following numbers:</h6>
  	<br />
  	<br />
  	<p>0728 276 362</p>
  	<br />
  	<br />
  	<p>0724 958 785</p>
  	<br />
  	<br />
  	<p>0722 789 738</p>
  	<br />
  	
  	<h6>You can also reach us via email:</h6>
  	<p>charles@ishackproperties.com</p>
  	<br />
  	<br />
  	<p>ireneg@ishackproperties.com</p>
  	<br />
  	<br />
  	<p>info@ishackproperties.com</p>
  	
  	
  	
  </div>
  <div class="span2">
  	<p></p>
  </div>
</div>

app/views/properties/edit.html.erb
<div class="row">
  <div class="span2">
  	<p></p>
  </div>
  <div class="span8">
 	<%= form_for @property, :html => { :multipart => true }, :url => property_path(@property), :html => { :class => "edit_property", :id => "edit_property" } do |f| -%>
	  <input name="_method" type="hidden" value="put" />
	  <%= render :partial => "form", :locals => {:f => f} %>
	<% end -%>
  </div>
  <div class="span2">
  	<p></p>
  </div>
</div>

app/views/properties/index.html.erb
<div class="cont-fix">
	<h1 class="page-header scream-header">Our Properties</h1>
	<ul class="thumbnails">
		<% @properties.each do |property| -%>
		  	
			  <li class="span3">
			    <div class="thumbnail">
			      <h3>
			      	<%= property.name %>
			      </h3>
			      <%= link_to image_tag(property.assets.first.asset.url(:large)), property %>
			      
			      <p>
			      	<h6>
			      		From <%= number_to_currency(property.price) %>
			      	</h6>
			      	<%= truncate(strip_tags(property.description),:length => 100) %>
			    	<%= link_to 'More Details', property ,:class=>"label label-success"%>
			      </p>
			      
			      <% if user_signed_in? %>
			        <%= link_to "Edit", edit_property_path(property) %>
	      			<%= link_to "Destroy", property_path(property), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
				  <% end %>
			    </div>
			  </li>
		<% end -%>
	</ul>
	
</div>

app/views/properties/new.html.erb
<div class="row">
  <div class="span2">
  	<p></p>
  </div>
  <div class="span8">
 	<%= form_for @property, :html => { :multipart => true }, :url => properties_path, :html => { :class => :form } do |f| -%>
	  <%= render :partial => "form", :locals => {:f => f} %>
	<% end -%>
  </div>
  <div class="span2">
  	<p></p>
  </div>
</div>

app/views/properties/show.html.erb
<div class="row">
  <div class="span2">
  	<p></p>
  </div>
  <div class="span8">
 	<h1 class="page-header"><%= @property.name %></h1>

	<label class="label"><%= t("activerecord.attributes.property.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</label>
	<p><%= @property.description %></p>
	
	<label class="label"><%= t("activerecord.attributes.property.location", :default => t("activerecord.labels.location", :default => "Location")) %>:</label>
	<p><%= @property.location %></p>
	
	<label class="label"><%= t("activerecord.attributes.property.status", :default => t("activerecord.labels.status", :default => "Status")) %>:</label>
	<p><%= @property.status %></p>
	
	<label class="label"><%= t("activerecord.attributes.property.price", :default => t("activerecord.labels.price", :default => "Price")) %>:</label>
	<p><%= number_to_currency(@property.price) %></p>
	
	
	<div class="clearfix">
	    <h2 class="page-header"><%= @property.name %> Pictures</h2>	
		<ul class="thumbnails">
			<%= form_for @property, :html => { :multipart => true }, :url => property_path(@property), :html => { :class => "edit_property", :id => "edit_property" } do |f| -%>
	  				<input name="_method" type="hidden" value="put" />
			<%= f.fields_for :assets do |asset_fields| %>
				<% unless asset_fields.object.new_record? %>
				  <li class="span4">
				    <div class="thumbnail">
				      <%= link_to image_tag(asset_fields.object.asset.url(:large)), '#'%>
				      <h3>
				      	<%= @property.name %>
				      </h3>
				      <p>
				      	<%= truncate(strip_tags(asset_fields.object.caption),:length => 100) %>
				      </p>
				    </div>
				  </li>
				<% end %>
			<% end %>
		<% end -%>
		</ul>
	</div>
	<div class="form-actions">
	<%= link_to "Back to Properties", properties_path, :class => 'btn'  %>
	
	<% if user_signed_in? %>
		<%= link_to "Edit", edit_property_path(@property), :class => 'btn' %>
		<%= link_to "Delete", property_path(@property), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
	<% end %>
	</div>
  </div>
  <div class="span2">
  	<p></p>
  </div>
</div>